M48
; DRILL file {KiCad 9.0.2} date 2025-06-30T19:38:35+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-30T19:38:35+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X141.33Y-112.34
X151.49Y-112.34
X165.1Y-112.3
X175.26Y-112.3
T2
X146.41Y-112.34
X170.18Y-112.3
M30
